spring:
  application:
    name: dysjsjy-api-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dyapi
    username: root
    password: root
server:
  port: 7529
  servlet:
    context-path: /api
logging:
  level:
    org.springframework: DEBUG
